### ISSUE TITLE
graphqlUploadExpress and graphqlUploadKoa are missing in typings 

### ISSUE THREAD

**Issue by KillerCodeMonkey** [flash-oss/graphql-upload-minimal#29]
heyho,

thanks notifying me at graphql-upload about your package.
i just took a quick look at it and seems to work in general, but your index.d.ts is lacking the typings graphqlUploadExpress,graphqlUploadKoa. When trying to import them in a typescript project you get the error that they are not exported by the package.

**Comment by DanielHefti** [comment]
I have tried to implement the package in my apollo-server-express project and received the error below. It would be highly appreciated if the missing types could be added. 

`Module '"graphql-upload-minimal"' has no exported member 'graphqlUploadExpress'.ts(2305)`

**Comment by KillerCodeMonkey** [comment]
PS: I worked around by import * as graphqlUploadMinimal from
'graphql-upload-minimal' and then
graphqlUploadMinimal['graphqlUploadExpress']

Daniel Hefti ***@***.***> schrieb am Mo., 8. Aug. 2022, 16:28:

**Comment by koresar** [comment]
Hi guys.
I'm really clueless how to help you. I wish someone can submit a PR or something.

Meanwhile, I've published `@next` version: https://github.com/flash-oss/graphql-upload-minimal/releases/tag/v1.5.3-0
Could you please try it out and see if it works? (I'm very bad at TypeScript, so any help is appreciated.)

**Comment by DanielHefti** [comment]
I have tried it with the new @next version. I don't have any type errors anymore. But there is a strange behaviour with the file stream. 

In my resolver function the createReadStream has a length of 0 when I save it to a constant. I try to save the stream to a constant to avoid calling the createReadStream twice. I use the createReadStream once to generate a hash of the file name and once to process the upload itself. 

`   const { createReadStream, filename, mimetype, encoding } = await args.input.file
`
`    const stream = createReadStream()`

![image](https://user-images.githubusercontent.com/54998625/183588072-1b852019-32d0-43db-b993-ae9f5e83a252.png)

When I log the createReadStream directly to the console, everything is working. 

![image](https://user-images.githubusercontent.com/54998625/183592537-ab7662c1-a814-4b3f-89d6-8961cd3b4767.png)

Anyway, I don't think that this problem is anyhow related to the issue with the missing typings.

**Comment by KillerCodeMonkey** [comment]
@koresar thx. next version seems to work

**Comment by koresar** [comment]
> I use the createReadStream once to generate a hash of the file and once to process the upload itself.

This is your mistake @DanielHefti . You would need to pipe the stream through a function which calculates hash but does not consume the stream. First example I found: https://stackoverflow.com/a/59280825/188475

Thanks @KillerCodeMonkey 
Published as [1.5.3](https://github.com/flash-oss/graphql-upload-minimal/releases/tag/v1.5.3)

**Comment by Miljoen** [comment]
Even though this is closed, the error remained for my project.

I've submitted a PR that fixed this for me:
https://github.com/flash-oss/graphql-upload-minimal/pull/34
